name: trasia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.17.1
  geolocator: ^14.0.3
  http: ^1.6.0
  mapbox_maps_flutter:
    path: vendor/mapbox_maps_flutter
  supabase_flutter: ^2.16.0
  image_picker: ^1.2.3
  mobile_scanner: ^7.4.0
  fl_chart: ^1.2.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_stripe: 14.0.0
  flutter_local_notifications: 22.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/branding/logo_loading.gif
