org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.daemon.idletimeout=60000
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiamVlc2hlbiIsImEiOiJjbXJ0ZHF5NjAwMnBhMnpxeWQ3N3VkZHExIn0.oqRzrKb2b90d2yM42kCjMw